/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x7B, 0x98, 0x40, 0x80, 0x40, 0x83, 0x95, 0xA3}
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
// enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE

// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS

// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS

// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS

#define ENABLE_RGB_MATRIX_SPLASH

// #define ENABLE_RGB_MATRIX_MULTISPLASH

#define ENABLE_RGB_MATRIX_SOLID_SPLASH

// #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH